# -*- coding: utf-8 -*-
"""Pandas_Part-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fx8D1FXWrMHiWIVPZ1aVQHahFCdOkbop

**Group By Function**
"""

import pandas as pd
titanic = pd.read_csv("https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/titanic_train.csv")
titanic.head(10)

titanic.shape

df_query = titanic.query("Pclass == 1")
a = titanic.groupby("Survived")
a.apply(display)

b = titanic.groupby("Pclass")
b.apply(display)
b.count()

# print(a.ngroups)
# print(a.size())
# print(a.nunique())
# print(a["Age"].nlargest(3))
# a["Age"].nsmallest()

print(titanic["Fare"].nlargest()) ##Task 1 Answer

print(titanic["Fare"].nsmallest(1)) # Task 2 Answer

print(titanic["Age"].nsmallest(3)) # Task 3 Answer

titanic.groupby(['Survived','Pclass']).agg(['count'])

df2 = pd.read_csv('https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/titanic_train.csv')
# pd.pivot_table(df2, index = ['Sex'])
# pd.pivot_table(df2, index = ['Sex','Pclass'], aggfunc=['count'])
pd.pivot_table(df2, index = ['Sex', 'Pclass'], values =['Age','Survived'])

"""**Exercise 1**"""

df3 = pd.read_csv('https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/titanic_train.csv')
df3.head(5)

df3.groupby("PassengerId")

df3.groupby(['Survived','Pclass']).agg(['count'])

